Bundling numpy, scipy, etc. in a Heroku buildpack. (reverse-merged from commit 597f6f9bf5236a560ef653cc63fd69b2ccc3f9dd)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,107 +1,71 @@
 #!/usr/bin/env bash
 
-# This buildpack step is based on https://github.com/heroku/heroku-buildpack-python
-# and https://github.com/wyn/heroku-buildpack-python, slightly modified for my own
-# nefarious purposes for scikits.audiolab / consistency with heroku's buildpack
-# look and feel. If you're just looking for np/scipy use, I recommend
-# https://github.com/wyn/heroku-buildpack-python.
+# Usage:
+#
+#     $ bin/compile <build-dir> <cache-dir>
 
+
+# Fail fast and fail hard.
 set -eo pipefail
 
+# Prepend proper path for virtualenv hackery. This will be deprecated soon.
+export PATH=:/usr/local/bin:$PATH
+
 # Paths.
-BIN_DIR=$(cd $(dirname $0); pwd)
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
 CACHE_DIR=$2
-VENDOR_DIR=".heroku/vendor"
 
-# The detected application type (`Python`|`Python/Django`).
-NAME=$($BIN_DIR/detect $BUILD_DIR)
-
-# Where to store the Pip download cache.
 CACHED_DIRS=".heroku"
-PIP_DOWNLOAD_CACHE=${PIP_DOWNLOAD_CACHE:-$CACHE_DIR/pip_downloads}
 
 # Static configurations for virtualenv caches.
-LEGACY_VIRTUALENV_LOC="."
-MODERN_VIRTUALENV_LOC=".heroku/venv"
-LEGACY_VIRTUALENV_DIRS="bin include lib"
-LEGACY_VIRTUALENV_TRIGGER="lib/python2.7"
+VIRTUALENV_LOC=".heroku/venv"
+LEGACY_TRIGGER="lib/python2.7"
+PROFILE_PATH="$BUILD_DIR/.profile.d/python.sh"
+
+# Python version. This will be used in the future to specify custom Pythons.
+DEFAULT_PYTHON_VERSION="python-2.7.4"
+PYTHON_EXE="/app/.heroku/python/bin/python"
+PIP_VERSION="1.3.1"
+DISTRIBUTE_VERSION="0.6.36"
 
 # Sanitizing environment variables.
-unset GIT_DIR
-unset PYTHON_HOME
-unset PYTHONPATH
+unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
 
-export PIP_DOWNLOAD_CACHE
-export BUILD_DIR
+# We'll need to send these statics to other scripts we `source`.
+export BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH
 
 # Syntax sugar.
-indent () {
-  RE="s/^/       /"
-  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
-}
+source $BIN_DIR/utils
 
-puts () {
-  printf -- "$1 "
-  shift 1
+# Directory Hacks for path consistiency.
+APP_DIR='/app'
+TMP_APP_DIR=$CACHE_DIR/tmp_app_dir
 
-  if [ -n "$3" ]; then
-    printf -- "\033[$1m[$2] \033[0m"
-    shift 1
-  fi
+# Copy Anvil app dir to temporary storage...
+mkdir -p $TMP_APP_DIR
+deep-mv $APP_DIR $TMP_APP_DIR
 
-  shift 1
+# Copy Application code in.
+deep-mv $BUILD_DIR $APP_DIR
 
-  echo "$@"
-}
+# Set new context.
+ORIG_BUILD_DIR=$BUILD_DIR
+BUILD_DIR=$APP_DIR
 
-pipe-step () {
-  if [ ! -t 0 ]; then
-    while read data; do
-      if [ ! -z "$data" ]; then
-        if [ -n "$1" ]; then
-          puts-step $1 "$data"
-        else
-          puts-step "$data"
-        fi
-      fi
-    done
-  fi
-}
-
-pipe-warn () {
-  if [ ! -t 0 ]; then
-    while read data; do
-      if [ ! -z "$data" ]; then
-        if [ -n "$1" ]; then
-          puts-warn $1 "$data"
-        else
-          puts-warn "$data"
-        fi
-      fi
-    done
-  fi
-}
-
-puts-step () {
-  puts "----->" "32" "$@"
-}
-
-puts-warn () {
-  puts "!     " "31" "$@"
-}
-
-virtualenv () {
-  python "$ROOT_DIR/vendor/virtualenv-1.7/virtualenv.py" "$@"
-}
-
-##############################################
-# Front matter.                              #
-##############################################
+# Prepend proper path buildpack use.
+export PATH=$BUILD_DIR/.heroku/python/bin:$PATH
+export PYTHONUNBUFFERED=1
+export LANG=en_US.UTF-8
+export LIBRARY_PATH=/app/.heroku/vendor/lib
+export LD_LIBRARY_PATH=/app/.heroku/vendor/lib
 
 # Switch to the repo's context.
 cd $BUILD_DIR
+
+# Experimental pre_compile hook.
+source $BIN_DIR/steps/hooks/pre_compile
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
@@ -109,155 +73,123 @@ if [ ! -f requirements.txt ]; then
   echo "-e ." > requirements.txt
 fi
 
-# Cache / heroku folder.
+# If no runtime given, assume default version.
+if [ ! -f runtime.txt ]; then
+  puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
+  echo $DEFAULT_PYTHON_VERSION > runtime.txt
+fi
+
+# ### The Cache
 mkdir -p $CACHE_DIR
-mkdir -p .heroku
-mkdir -p $VENDOR_DIR
 
-# Nice defaults.
-LEGACY_VIRTUALENV=false
-VIRTUALENV_LOC=$MODERN_VIRTUALENV_LOC
+# Purge "old-style" virtualenvs.
+[ -d $CACHE_DIR/$LEGACY_TRIGGER ] && rm -fr $CACHE_DIR/.heroku/bin $CACHE_DIR/.heroku/lib $CACHE_DIR/.heroku/include
+[ -d $CACHE_DIR/$VIRTUALENV_LOC ] && rm -fr $CACHE_DIR/.heroku/venv $CACHE_DIR/.heroku/src
 
-# Support "old-style" virtualenvs.
-if [ -d $CACHE_DIR/$LEGACY_VIRTUALENV_TRIGGER ]; then
-  LEGACY_VIRTUALENV=true
-  VIRTUALENV_LOC=$LEGACY_VIRTUALENV_LOC
-  CACHED_DIRS=$LEGACY_VIRTUALENV_DIRS
-
-  # Warn for a checked-in virtualenv.
-  if [ -d "lib" ] || [ -d "bin" ]; then
-    puts-warn "You have a virtualenv checked in. You should ignore the appropriate paths in your repo. See http://devcenter.heroku.com/articles/gitignore for more info."
-  fi
-
-  # Reject a conflicting checked-in virtualenv.
-  if [ -f "lib/python2.7" ]; then
-    puts-warn "Checked-in virtualenv conflict."
-    exit 1;
-  fi
-fi
-
-##############################################
-# Restore cache.                             #
-##############################################
-
-if [ ! -n "$EMPTYCACHE" ]; then
-  puts-step "Restoring cache from $CACHE_DIR."
-
-  for dir in $CACHED_DIRS; do
-    cp -R $CACHE_DIR/$dir . &> /dev/null || true
-  done
-else
-  puts-step "Ignoring cache (EMPTYCACHE=$EMPTYCACHE)."
-  rm -rf $CACHE_DIR
-fi
-
-##############################################
-# Create the virtualenv. Rebuild if corrupt. #
-##############################################
+# Restore old artifacts from the cache.
+for dir in $CACHED_DIRS; do
+  cp -R $CACHE_DIR/$dir . &> /dev/null || true
+done
 
 set +e
+# Create set-aside `.heroku` folder.
+mkdir .heroku &> /dev/null
+set -e
 
-echo $PATH
-puts-step "Creating virtualenv ($(virtualenv --version))."
+mkdir -p $(dirname $PROFILE_PATH)
 
-if [ -e $VIRTUALENV_LOC ]; then
-  puts-step "Using cached virtualenv."
+set +e
+PYTHON_VERSION=$(cat runtime.txt)
+
+# Install Python.
+if [ -f .heroku/python-version ]; then
+  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
+    puts-step "Found $(cat .heroku/python-version), removing."
+    rm -fr .heroku/python
+  else
+    SKIP_INSTALL=1
+  fi
+fi
+
+
+if [ ! "$SKIP_INSTALL" ]; then
+  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+  curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
+  if [[ $? != 0 ]] ; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    exit 1
+  fi
+  mv python .heroku/python
+
+  # Record for future reference.
+  echo $PYTHON_VERSION > .heroku/python-version
+  FRESH_PYTHON=true
+
+  hash -r
 else
-  # Try to create the virtualenv.
-  OUT=$(virtualenv --never-download --prompt='(venv) ' $VIRTUALENV_LOC 2>&1)
+  puts-step "Using Python runtime ($PYTHON_VERSION)"
+fi
 
-  # If there's an error, purge and recreate.
-  [ $? -ne 0 ] && {
-    puts-warn "virtualenv" "Virtualenv corrupt, rebuilding."
+# If Pip isn't up to date:
+if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
+  WORKING_DIR=$(pwd)
 
-    for dir in $VIRTUALENV_DIRS; do
-      rm -fr $dir &> /dev/null || true
-    done
+  # Prepare it for the real world
+  puts-step "Installing Distribute ($DISTRIBUTE_VERSION)"
+  cd $ROOT_DIR/vendor/distribute-$DISTRIBUTE_VERSION/
+  python setup.py install &> /dev/null
+  cd $WORKING_DIR
 
-    OUT=$(virtualenv --never-download  --prompt='(venv) ' $VIRTUALENV_LOC)
-  }
-
-  #echo "$OUT" | indent
+  puts-step "Installing Pip ($PIP_VERSION)"
+  cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
+  python setup.py install &> /dev/null
+  cd $WORKING_DIR
 fi
 
 set -e
+hash -r
 
-##############################################
-# Activate virtualenv.                       #
-##############################################
+# Pylibmc support.
+# See [`bin/steps/pylibmc`](pylibmc.html).
+source $BIN_DIR/steps/pylibmc
 
-puts-step "Activating virtualenv."
-source $VIRTUALENV_LOC/bin/activate
-
-# In case we restored a cached virtualenv, we
-# need to remove the old venv/bin from our
-# PATH, since the /tmp/ directories change
-# every push. Otherwise, we won't be able to
-# find pip.
-
-echo $PATH
-export PATH=$PWD/$VIRTUALENV_LOC/bin:`echo $PATH | awk -v RS=: -v ORS=: '/tmp/ {next} {print}' | sed 's/:*$//'`
-echo $PATH
-
-
-##############################################
-# Compile specific dependencies before Pip.  #
-##############################################
-
-source $BIN_DIR/steps/scipy
-
-##############################################
-# Install Mercurial if needed.               #
-##############################################
-
+# Install Mercurial if it appears to be required.
 if (grep -Fiq "hg+" requirements.txt) then
-  puts-step "pip" "Installing Mercurial."
-  pip install --use-mirrors mercurial 2>&1 >/dev/null | pipe-warn 'pip'
+  /app/.heroku/python/bin/pip install --use-mirrors mercurial | cleanup | indent
 fi
 
-##############################################
-# Install Python dependencies with Pip.      #
-##############################################
+# Install dependencies with Pip.
+puts-step "Installing dependencies using Pip ($PIP_VERSION)"
+/app/.heroku/python/bin/pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | cleanup | indent
 
-puts-step "pip" "Installing Python dependencies."
+# Django collectstatic support.
+source $BIN_DIR/steps/collectstatic
 
-# Prevent pip from trying to install packages we already installed manually.
-cat requirements.txt | grep -vie "numpy" -vie "scipy" > requirements2.txt
-pip install --use-mirrors -r requirements2.txt --src ./.heroku/src | indent
+# ### Finalize
+#
 
-##############################################
-# Django-specific.                           #
-##############################################
+# Set context environment variables.
+set-env PATH '$HOME/.heroku/python/bin:$PATH'
+set-env PYTHONUNBUFFERED true
+set-env PYTHONHOME /app/.heroku/python
+set-default-env LIBRARY_PATH /app/.heroku/vendor/lib
+set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib
+set-default-env LANG en_US.UTF-8
+set-default-env PYTHONHASHSEED random
+set-default-env PYTHONPATH /app/
 
-if [ "$NAME" = "Python/Django" ] && ! [ "$DISABLE_INJECTION" ]; then
-  source $BIN_DIR/steps/django
-fi
 
-##############################################
-# Make virtualenv paths relative.            #
-##############################################
+# Experimental post_compile hook.
+source $BIN_DIR/steps/hooks/post_compile
 
-set +e
-
-OUT=$(virtualenv --relocatable $VIRTUALENV_LOC)
-[ $? -ne 0 ] && {
-  puts-warn "Error making virtualenv relocatable"
-  echo "$OUT" | pipe-warn
-  exit 1
-}
-
-set -e
-
-##############################################
-# Store everything in the cache.             #
-##############################################
-
-puts-step "Updating cache."
-
+# Store new artifacts in cache.
 for dir in $CACHED_DIRS; do
   rm -rf $CACHE_DIR/$dir
   cp -R $dir $CACHE_DIR/
 done
 
-# Remove vendor dir after caching to reduce slug size.
-rm -rf $VENDOR_DIR
+# ### Fin.
+
+deep-mv $BUILD_DIR $ORIG_BUILD_DIR
+deep-mv $TMP_APP_DIR $APP_DIR
